CREATE DATABASE "onlive";

-- TABELLA PORTE JAMULUS SERVER
CREATE TABLE onlive.JPORTS (
	PORT int NOT NULL,
	RUNNING BIT NOT NULL,

	PRIMARY KEY (PORT)
);
INSERT INTO onlive.JPORTS VALUES (22124, 0);
INSERT INTO onlive.JPORTS VALUES (22125, 0);
INSERT INTO onlive.JPORTS VALUES (22126, 0);
INSERT INTO onlive.JPORTS VALUES (22127, 0);
INSERT INTO onlive.JPORTS VALUES (22128, 0);
INSERT INTO onlive.JPORTS VALUES (22129, 0);
INSERT INTO onlive.JPORTS VALUES (22130, 0);
INSERT INTO onlive.JPORTS VALUES (22131, 0);
INSERT INTO onlive.JPORTS VALUES (22132, 0);
INSERT INTO onlive.JPORTS VALUES (22133, 0);

-- TABELLA EVENTS
CREATE TABLE onlive.EVENTS (
	ID int AUTO_INCREMENT,
	NAME VARCHAR(64) NOT NULL,
	DESCRIPTION VARCHAR(128) NOT NULL,
	DATE_SET DATETIME NOT NULL,
	DATE_START DATETIME,
	DATE_STOP DATETIME,
	PID int,
	PORT INT,
	RUNNING BIT NOT NULL,

	PRIMARY KEY (ID),
    CONSTRAINT FK_JPORTS_EVENTS FOREIGN KEY (PORT)
    REFERENCES onlive.JPORTS(PORT)

);

-- TABELLA USERS
CREATE TABLE onlive.USERS (
	USERNAME VARCHAR(16) NOT NULL,
	NAME VARCHAR(32) NOT NULL,
	SURNAME VARCHAR(32) NOT NULL,
	PASSWORD VARCHAR(256) NOT NULL,
	EMAIL VARCHAR(32) NOT NULL,
	CODICE_TOKEN VARCHAR(16),
	IS_ACTIVE BIT NOT NULL, 
	DATE_CREATE DATE NOT NULL,
	DATE_DELETE DATE,
	
	PRIMARY KEY (USERNAME)
);

