DROP TABLE ONSTAGE.GROUPS_GENRES;

DROP TABLE ONSTAGE.USERS_MUSIC_ROLES;

DROP TABLE ONSTAGE.USERS_GENRES;

DROP TABLE ONSTAGE.EVENTS_GENRES;

DROP TABLE ONSTAGE.GROUPS_MEMBERS_GROUPS_ROLES;

DROP TABLE ONSTAGE.GROUPS_MEMBERS;

DROP TABLE ONSTAGE.FAVORITES_GROUPS;

DROP TABLE ONSTAGE.GROUPS;

DROP TABLE ONSTAGE.GROUPS_ROLES;

DROP TABLE ONSTAGE.GENRES;

DROP TABLE ONSTAGE.MUSIC_ROLES;

DROP TABLE ONSTAGE.SESSIONS;

DROP TABLE ONSTAGE.USERS;

DROP TABLE ONSTAGE.EVENTS;

DROP TABLE ONSTAGE.JPORTS;

DROP DATABASE ONSTAGE;
